# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [2]:
import numpy as np

# Create the array
arr1 = np.arange(1, 13)

# Reshape the array
res = arr1.reshape((3, 4))

# Print the result
print(res)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
import numpy as np

# Original code
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[13, 14, 15]])

hor = np.concatenate((res, array1), axis=0)
ver = np.concatenate((res, array2.T), axis=1)

# Modified code
hor = np.vstack((res, array1))
ver = np.hstack((res, array2.T))

print("Horizontal Concatenation:")
print(hor)
print("\nVertical Concatenation:")
print(ver)


Horizontal Concatenation:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]

Vertical Concatenation:
[[ 1  2  3  4 13]
 [ 5  6  7  8 14]
 [ 9 10 11 12 15]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [4]:
# Code Here
def classify_emails(emails):
    # Define keyword lists
    important_keywords = ['note', 'urgent', 'important', 'action required']
    promotions_keywords = ['sale', 'deal', 'promotion', 'discount']
    spam_keywords = ['win', 'lottery', 'prize', 'free', 'click here']

    # Initialize lists to store classified emails
    important_emails = []
    promotions_emails = []
    spam_emails = []

    # Iterate through each email
    for email in emails:
        # Convert email to lowercase for case-insensitive matching
        lower_case_email = email.lower()

        # Check if the email contains any important keywords
        if any(keyword in lower_case_email for keyword in important_keywords):
            important_emails.append(email)
        # Check if the email contains any promotions keywords
        elif any(keyword in lower_case_email for keyword in promotions_keywords):
            promotions_emails.append(email)
        # Check if the email contains any spam keywords
        elif any(keyword in lower_case_email for keyword in spam_keywords):
            spam_emails.append(email)

    # Return classified emails
    return important_emails, promotions_emails, spam_emails

# Example usage:
emails_to_classify = [
    "Urgent: Action required on your account",
    "Exclusive deal for you! Save 20% now!",
    "Congratulations! You won a free vacation",
    "Important update about your subscription",
    "Check out our latest promotions and discounts"
]

# Classify emails
important, promotions, spam = classify_emails(emails_to_classify)

# Print results
print("Important Emails: ", important)
print("\nPromotions Emails: ", promotions)
print("\nSpam Emails: ", spam)


Important Emails:  ['Urgent: Action required on your account', 'Important update about your subscription']

Promotions Emails:  ['Exclusive deal for you! Save 20% now!', 'Check out our latest promotions and discounts']

Spam Emails:  ['Congratulations! You won a free vacation']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [ ]:
# Code Here
dict_sp = {
    'hello': 'hola',
    'bye': 'adios',
    'thanks': 'gracias',
    'please': 'por favor',
    'yes': 'si',
    'no': 'no',
    'love': 'amor'
}

while True:
    word = input("Enter the word you want to translate (or enter 'exit' to quit): ").lower()

    if word == 'exit':
        print("Exiting translation program. Adios!")
        break

    if word in dict_sp:
        print(f"The Spanish translation of '{word}' is: {dict_sp[word]}")
    else:
        print("Sorry, the translation for this word is not available.")


Enter the word you want to translate (or enter 'exit' to quit): hola
Sorry, the translation for this word is not available.
Enter the word you want to translate (or enter 'exit' to quit): hello
The Spanish translation of 'hello' is: hola


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [6]:
import pandas as pd
data=pd.read_csv('/content/vgsalesGlobale.csv',sep=',',index_col='Rank')
data

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
Rank                 
1             82.74  
2             40.24  
3             35.82  
4             33.00  
5             31.37  
...             ...  
16596          0.01  
16597          0.01  
16598          0.01  
16599          0.01  
16600          0.01  

[16598 rows x 10 columns]

In [7]:
print("The total global sales are: ",data['Global_Sales'].sum())


The total global sales are:  8920.44


In [10]:
max1=data.loc[data['Global_Sales'].idxmax()]
print("The game that has the highest global sale is: ",max1['Name'])
print("Highest sale is: ",data['Global_Sales'].max())

The game that has the highest global sale is:  Wii Sports
Highest sale is:  82.74


In [12]:
print("The average sales for NA region is: ",data['NA_Sales'].mean())
print("The average sales for EU region is: ",data['EU_Sales'].mean())
print("The average sales for JP region is: ",data['JP_Sales'].mean())
print("The average sales for other regions is: ",data['Other_Sales'].mean())

The average sales for NA region is:  0.26466742981082064
The average sales for EU region is:  0.14665200626581515
The average sales for JP region is:  0.077781660441017
The average sales for other regions is:  0.0480630196409206


In [18]:
genre=data.groupby('Genre')['Global_Sales'].sum()
top5=genre.nlargest(5)
print("The top 5 genre according to global sales are: ",top5)

The top 5 genre according to global sales are:  Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [19]:
print("The total sales of NA region are: ",data['NA_Sales'].sum())
print("The total sales of EU region are: ",data['EU_Sales'].sum())
print("The total sales of JP region are: ",data['JP_Sales'].sum())
print("The total sales of other regions are: ",data['Other_Sales'].sum())
pop=data.groupby('Genre')['NA_Sales'].sum()
top=pop.nlargest(1)
print("The top genre of NA region is: ",top)

The total sales of NA region are:  4392.950000000001
The total sales of EU region are:  2434.1299999999997
The total sales of JP region are:  1291.0200000000002
The total sales of other regions are:  797.7500000000001
The top genre of NA region is:  Genre
Action    877.83
Name: NA_Sales, dtype: float64


In [20]:
data.tail(10)

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
Rank                              
16591          0.0          0.01  
16592          0.0          0.01  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01  
16598          0.0          0.01  
16599          0.0          0.01  
16600          0.0          0.01

In [21]:
platform=data.groupby('Platform')['Global_Sales'].sum()
top3=platform.nlargest(3)
print("The top 3 platforms according to global sales are: ",top3)

The top 3 platforms according to global sales are:  Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [22]:
total=data['Global_Sales'].sum()
share=(genre/total)*100
print("Market share of each genre: ")
print(share)


Market share of each genre: 
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [24]:
relation=data['NA_Sales'].corr(data['EU_Sales'])
print("Corelation between NA_Sales and EU_Sales is: ",relation)

Corelation between NA_Sales and EU_Sales is:  0.7677267483702631


In [ ]:

import numpy as np

# Original code
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[13, 14, 15]])

hor = np.concatenate((res, array1), axis=0)
ver = np.concatenate((res, array2.T), axis=1)

# Modified code
hor = np.vstack((res, array1))
ver = np.hstack((res, array2.T))

print("Horizontal Concatenation:")
print(hor)
print("\nVertical Concatenation:")
print(ver)
